services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - sqlite-data:/app/data
      - uploads-data:/app/public/uploads
    environment:
      - AUTH_SECRET=McQZE5r3jFE4NxaiuNcYeQpG4NXc36fT0y3VWluVikk=
      - NEXTAUTH_SECRET=McQZE5r3jFE4NxaiuNcYeQpG4NXc36fT0y3VWluVikk=
      - AUTH_URL=http://rdev.buq.cz:3000
      - NEXTAUTH_URL=http://rdev.buq.cz:3000
      - DATABASE_URL=file:/app/data/prod.db
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped

volumes:
  sqlite-data:
  uploads-data:
